// <auto-generated />
namespace WebStoreWeb.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class addingModelArraysinProductClass : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(addingModelArraysinProductClass));
        
        string IMigrationMetadata.Id
        {
            get { return "202006112017070_adding Model Arrays in Product Class"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
